package com.vyllo.music.data.repository.delegates

import com.vyllo.music.core.security.SecureLogger
import com.vyllo.music.data.LyricsEngine
import com.vyllo.music.domain.model.LyricsResponse
import com.vyllo.music.domain.model.LyricsResult
import com.vyllo.music.domain.model.LyricsStatus
import com.vyllo.music.domain.model.SyncedLyricLine
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class SubtitleLyricsDelegate @Inject constructor(
    private val streamSelector: StreamSelector
) {

    fun selectBestSubtitles(streams: List<SubtitlesStream>, targetLanguage: String?): SubtitlesStream? {
        if (streams.isEmpty()) return null

        val supportedStreams = streams.filter {
            (it.format == org.schabi.newpipe.extractor.MediaFormat.VTT ||
            it.format == org.schabi.newpipe.extractor.MediaFormat.SRT) &&
            !it.url.isNullOrBlank()
        }

        if (supportedStreams.isEmpty()) return null

        val langLower = targetLanguage?.lowercase()

        if (!langLower.isNullOrBlank()) {
            supportedStreams.firstOrNull {
                !it.isAutoGenerated &&
                (it.languageTag.lowercase().contains(langLower) || it.displayLanguageName.lowercase().contains(langLower))
            }?.let { return it }
        }

        supportedStreams.firstOrNull {
            !it.isAutoGenerated &&
            (it.languageTag.lowercase().startsWith("en") || it.displayLanguageName.lowercase().contains("english"))
        }?.let { return it }

        if (!langLower.isNullOrBlank()) {
            supportedStreams.firstOrNull {
                it.isAutoGenerated &&
                (it.languageTag.lowercase().contains(langLower) || it.displayLanguageName.lowercase().contains(langLower))
            }?.let { return it }
        }

        supportedStreams.firstOrNull {
            it.isAutoGenerated &&
            (it.languageTag.lowercase().startsWith("en") || it.displayLanguageName.lowercase().contains("english"))
        }?.let { return it }

        supportedStreams.firstOrNull { !it.isAutoGenerated }?.let { return it }

        return supportedStreams.firstOrNull()
    }

    fun parseSubtitleTimestamp(timeStr: String): Long? {
        val clean = timeStr.trim().replace(',', '.')
        val parts = clean.split('.')
        val timeParts = parts[0].split(':')
        if (timeParts.size < 2) return null
        val ms = parts.getOrNull(1)?.padEnd(3, '0')?.take(3)?.toLongOrNull() ?: 0L
        val secs = timeParts.last().toLongOrNull() ?: return null
        val mins = timeParts[timeParts.size - 2].toLongOrNull() ?: return null
        val hrs = if (timeParts.size > 2) timeParts[timeParts.size - 3].toLongOrNull() ?: 0L else 0L
        return hrs * 3600000L + mins * 60000L + secs * 1000L + ms
    }

    fun parseSubtitles(content: String): List<SyncedLyricLine> {
        val lines = content.lines()
        val list = mutableListOf<SyncedLyricLine>()
        var currentTimestamp: Long? = null
        val currentText = StringBuilder()

        for (line in lines) {
            val trimmed = line.trim()
            if (trimmed.contains("-->")) {
                if (currentTimestamp != null && currentText.isNotEmpty()) {
                    val text = cleanSubtitleText(currentText.toString())
                    if (text.isNotBlank()) {
                        list.add(SyncedLyricLine(currentTimestamp, text))
                    }
                    currentText.clear()
                }
                val parts = trimmed.split("-->")
                if (parts.isNotEmpty()) {
                    currentTimestamp = parseSubtitleTimestamp(parts[0])
                }
            } else if (trimmed.isBlank()) {
                if (currentTimestamp != null && currentText.isNotEmpty()) {
                    val text = cleanSubtitleText(currentText.toString())
                    if (text.isNotBlank()) {
                        list.add(SyncedLyricLine(currentTimestamp, text))
                    }
                    currentText.clear()
                }
                currentTimestamp = null
            } else if (trimmed.toLongOrNull() != null) {
                continue
            } else if (trimmed.equals("WEBVTT", ignoreCase = true) || trimmed.startsWith("NOTE")) {
                continue
            } else {
                if (currentTimestamp != null) {
                    if (currentText.isNotEmpty()) currentText.append(" ")
                    currentText.append(trimmed)
                }
            }
        }
        if (currentTimestamp != null && currentText.isNotEmpty()) {
            val text = cleanSubtitleText(currentText.toString())
            if (text.isNotBlank()) {
                list.add(SyncedLyricLine(currentTimestamp, text))
            }
        }
        return list
    }

    fun cleanSubtitleText(text: String): String {
        return text.replace(Regex("<[^>]*>"), "").trim()
    }

    suspend fun downloadSubtitleContent(url: String): String? = withContext(Dispatchers.IO) {
        SecureLogger.d("MusicRepositoryImpl") { "Downloading subtitles from $url" }
        streamSelector.fetchUrlContent(url, "Mozilla/5.0 (Windows NT 10.0; Win64; x64)")
    }

    fun buildSubtitleResponse(
        subContent: String,
        syncedLines: List<SyncedLyricLine>,
        title: String,
        artist: String,
        duration: Long,
        extTitle: String?,
        extArtist: String?,
        extAlbum: String?,
        extLanguage: String?
    ): LyricsResponse {
        val plainText = syncedLines.joinToString("\n") { it.content }
        val detectedLangs = LyricsEngine.detectLanguage(plainText)

        val lyricsResult = LyricsResult(
            id = -1L,
            trackName = extTitle ?: title,
            artistName = extArtist ?: artist,
            albumName = extAlbum,
            duration = duration,
            instrumental = false,
            plainLyrics = plainText,
            syncedLyrics = subContent
        )

        return LyricsResponse(
            success = true,
            strategy = "YOUTUBE_SUBTITLES",
            result = lyricsResult,
            results = listOf(lyricsResult),
            plainLyrics = plainText,
            syncedLines = syncedLines,
            languages = if (extLanguage != null) listOf(extLanguage.lowercase()) else detectedLangs,
            lyricsStatus = LyricsStatus(
                hasPlain = true,
                hasSynced = true,
                isInstrumental = false
            )
        )
    }
}
